name: Build Windows Executable

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v3  # Set up Python
        with:
          python-version: '3.13'  # Specify Python version

      - name: Install Poetry
        run: |
          pip install poetry  # Install Poetry

      - name: Install dependencies
        run: |
          poetry install  # Install dependencies using Poetry

      - name: Build executable
        run: |
          poetry run pyinstaller --onefile --name upload_images upload_all_images_in_markdown/main.py  # Build the executable

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Upload the generated .exe file
        with:
          name: upload-images.exe
          path: upload_all_images_in_markdowndist/upload-images.exe 